name = "SFHWorkflows"
uuid = "9f162cfb-b9f3-4dd2-bb0f-c8f5cc5047ef"
authors = ["cgarling <chris.t.garling@gmail.com> and contributors"]
version = "0.1.0"

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
BolometricCorrections = "37ee4594-8306-40da-a4c2-d7ed95560e0b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
InitialMassFunctions = "e9251ff4-c148-4db3-bf46-89407750fae0"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
PDFmerger = "3beb2ed1-af7d-458f-b727-6e9beb3586c0"
PlotUtils = "995b91a9-d308-5afd-9ec6-746e21dbc043"
StarFormationHistories = "774d3ad4-2d55-48fa-ab42-467705ebff24"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StellarTracks = "2b4a1a39-e20a-4324-9c0b-7d841c062f62"
TypedTables = "9d95f2ec-7b3d-5a63-8d20-e2491e220bb9"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
ArgCheck = "2"
BolometricCorrections = "0.1"
CairoMakie = "0.15"
DataInterpolations = "8"
DelimitedFiles = "<0.0.1, 1"
InitialMassFunctions = "0.1"
Logging = "<0.0.1, 1"
Makie = "0.24"
PDFmerger = "0.3"
PlotUtils = "1"
StarFormationHistories = "1"
StatsBase = "0.34"
StellarTracks = "1"
TypedTables = "1"
YAML = "0.4"
julia = "1.10"
