data:
  path: /home/cgarling/Work/UVA/Projects/SFH/aquarius/data # Common path prefix to add to photometry_file and ast_file
  fp: Float64 # Data type to parse floating point numbers as; either Float32 or Float64 (Float32 generally faster, rare convergence issues)
  photometry:
      photometry_file: phot.dat # One column per filter, apparent magnitudes
      filters: F475W, F814W # Filter name for each column in photometry_file, comma separated
  ASTs:
    # For two filters, ast_file has 4 columns with convention
    # (inputmag1, inputmag2, (outmag1 - inputmag1), (outmag2 - inputmag2)
    ast_file: fake.dat
    badval: 99.999 # values of (out-in) columns that indicates a non-detection
    minerr: 0.01   # minimum photometric error to allow in model
    maxerr: 0.25   # maximum photometric error to allow in model
  binning:
    # range(a, b; length=c) gives uniform range from a to b with number of steps = c
    ybins: range(20.5, 28.0; length=150)
    xbins: range(-0.75, 2.5; length=75)
    yfilter: F814W
    xcolor: F475W, F814W

imf:
  # Valid models: Kroupa2001, Chabrier2001BPL, Chabrier2001LogNormal, Chabrier2003, Chabrier2003System, Salpeter1955
    model: Kroupa2001
    mmin: 0.08  # Minimum stellar mass
    mmax: 100.0 # Maximum stellar mass

binaries:
  # Valid models: NoBinaries, RandomBinaryPairs
  # model: RandomBinaryPairs
  # binary_fraction: 0.4
  model: NoBinaries

stellartracks:
  # One entry per stellar track library you want to run the SFH fit with.
  # Name either parsec, mist, bastiv1, bastiv2 (case insensitive).
  # Use of bastiv1 (old basti models) is discouraged. 
  # parsec takes no arguments. 
  # mist takes vvcrit argument, either 0.0 (non-rotating) or 0.4 (rotating).
  # bastiv2 takes several arguments, for valid options see https://cgarling.github.io/StellarTracks.jl/stable
  # alpha_fe: [alpha/Fe], default 0.0
  # canonical: Whether to use models with convective overshooting (false) or without (true), default false
  # diffusion: Whether to use models with atomic diffusion (true) or without (false), default true
  # yp: primordial helium abundance, default 0.247
  # eta: Reimers mass-loss parameter, default 0.3
  track1:
    name: PARSEC
  track2:
    name: MIST
    vvcrit: 0.0
  track3: 
    name: BASTIV2
    alpha_fe: 0.0
    canonical: false
    diffusion: true
    yp: 0.247
    eta: 0.3
  logAge: range(6.6, 10.13; step=0.05) # Specification for grid of log10(age [yr]) values. Either a range object or a discrete vector
  # logAge: [9.0, 9.5, 10.0] # Example for a discrete vector
  MH: range(-2.4, 0.0; step=0.1) # Specification for grid of logarithmic metallicities [M/H]; for scaled solar abundances, [M/H] = [Fe/H].
  # MH: [-2.0, -1.5, -1.0] # Example for a discrete vector

bolometriccorrections:
# The SFH will be measured for each combination of track (defined above) and bolometric correction library (defined here)
# See documentation https://cgarling.github.io/BolometricCorrections.jl/stable/ for names of available filtersets
  bc1: 
    name: YBC
    filterset: acs_wfc
  bc2: 
    name: MIST
    filterset: acs_wfc

properties:
  Av: 0.13466152995504851 # V-band extinction
  distance_modulus: 24.95
  Mstar: 2.6e6 # Stellar mass to set normalization of initial SFH guess; order-of-magnitude

metallicity: # Options are LinearAMR, LogarithmicAMR, PowerLawMZR, examples below
  name: PowerLawMZR # [M/H] = alpha * (log10(M_*(t)) - log10(mstar0)) + beta
  alpha: # power-law slope parameter
    x0: 1.0 # Initial guess
    free: true # Whether to parameter should be free to vary (true) or fixed (false)
  beta: # power-law intercept parameter
    x0: -1.5 # Initial guess
    free: true
  mstar0: 1e6 # Stellar mass normalization; by definition, metallicity is beta at mstar0. Generally leave this be.
  std: 0.1 # Gaussian σ for the spread in metallicity at fixed time

# metallicity:
#   name: LinearAMR # [M/H] = alpha * (T_max - t) + beta, [M/H] is logarithmic metallicity
#   alpha:
#     x0: 0.1
#     free: true
#   beta:
#     x0: -1.5
#     free: true
#   Tmax: 13.7 # Highest valid lookback time, typically the age of the Universe, in units of Gyr.
#   std: 0.1

# metallicity:
#   name: LogarithmicAMR # Z = α * (T_max - t_j) + β, Z is metal mass fraction
#   alpha:
#     x0: 1e-4
#     free: true
#   beta:
#     x0: 5e-5
#     free: true
#   Tmax: 13.7 # Highest valid lookback time, typically the age of the Universe, in units of Gyr.
#   std: 0.1

plotting:
  diagnostics: true # Creates diagnostics.pdf in output.path (see below) showing derived error and completeness functions

output:
  # Absolute or relative path to where you want the results (data files, plots, etc.) to be stored.
  # If path doesn't exist, it is created. 
  # Default "." indicates you want results stored in the directory that you are running the Julia process from.
  path: ./results
  # filename indicates the file (relative to above path) to write final SFH results to.
  # Additional results files below are constructed from filename via the pattern <basename>.<extension>
  # <basename>_mass.<extension> contains statistics on the total stellar mass formed in the SFH fits.
  filename: results.txt
